- name: Add k8s apt keyring
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    keyring: /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg
    state: present

- name: Adicionar o repositório do Kubernetes
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    state: present

- name: Install k8s packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet={{ K8S_VERSION }} 
    - kubeadm={{ K8S_VERSION }}
    - kubectl={{ K8S_VERSION }}
