- name: Template /etc/modules-load.d/k8s.conf
  template:
    src: ../templates/k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0755'
 
- name: Template /etc/sysctl.d/k8s.conf
  template:
    src: ../templates/k8s-sysctl.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0755'

- name: sysctl
  shell: "sysctl --system"

- name: "modprobe overlay"
  modprobe:
    name: overlay
    state: present

- name: "modprobe br_netfilter"
  modprobe:
    name: br_netfilter
    state: present
