- name: Disable IPv6tables and enable IPv4_forward
  sysctl: name={{ item }} value=1 state=present
  with_items:
   - net.bridge.bridge-nf-call-ip6tables 
   - net.bridge.bridge-nf-call-iptables
   - net.ipv4.ip_forward

- name: sysctl --system
  shell: sysctl --system 
