- hosts: master
  remote_user: ubuntu
  become: yes
  roles:
  - common
  - containerd
  - kubernetes
  tags: alltogether

- hosts: apiserver 
  remote_user: ubuntu
  become: yes
  roles:
  - master
  tags: apiserver

- hosts: master
  become: yes
  user: ubuntu
  tasks:
    - include_role:
        name: master
        tasks_from: token
  tags: token

- hosts: nodes
  become: yes
  user: ubuntu 
  roles:
  - nodes
  tags: nodes

- hosts: workers 
  become: yes
  user: ubuntu 
  roles:
  #- common 
  #- containerd  
  - kubernetes 
  tags: kubernetes 
